/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package views;

import domain.Camioneta;
import domain.Convertible;
import domain.Motocicleta;
import domain.Rastra;
import domain.Vehiculo;
import interfaces.ITaller;
import javax.swing.JOptionPane;

/**
 *
 * @author admin
 */
public class FormInsertarVehiculo extends javax.swing.JDialog {
    private ITaller taller = null; 
    /**
     * Creates new form FormInsertarCamioneta
     */
    public FormInsertarVehiculo(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        
        RadioButtonMonoplaza.setVisible(false);
        lblPais.setVisible(false);
        txtPais.setVisible(false);
        lblVelocidades.setVisible(false);
        sldVelocidades.setVisible(false);
        lblVolumenMaximo.setVisible(false);
        txtVolumenMaximo.setVisible(false);
        lblVolumenActual.setVisible(false);
        txtVolumenActual.setVisible(false);
        radioButtonLujo.setVisible(false);
        lblVagones.setVisible(false);
        txtVagones.setVisible(false);
        
        group1.add(moto);
        group1.add(camioneta);
        group1.add(convertible);
        group1.add(rastra);
    }

    public FormInsertarVehiculo(ITaller taller) {
        this(null, true);
        this.taller = taller;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        group1 = new javax.swing.ButtonGroup();
        txtChapa = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtColor = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtFechaFabricacion = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtCombustible = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtKilometraje = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtPrecioReparacion = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtCostoReparacion = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtFechaReparacion = new javax.swing.JTextField();
        btnLimpiar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblPais = new javax.swing.JLabel();
        txtPais = new javax.swing.JTextField();
        RadioButtonMonoplaza = new javax.swing.JRadioButton();
        moto = new javax.swing.JRadioButton();
        camioneta = new javax.swing.JRadioButton();
        convertible = new javax.swing.JRadioButton();
        rastra = new javax.swing.JRadioButton();
        lblVelocidades = new javax.swing.JLabel();
        sldVelocidades = new javax.swing.JSlider();
        lblVolumenMaximo = new javax.swing.JLabel();
        txtVolumenMaximo = new javax.swing.JTextField();
        lblVolumenActual = new javax.swing.JLabel();
        txtVolumenActual = new javax.swing.JTextField();
        radioButtonLujo = new javax.swing.JRadioButton();
        lblVagones = new javax.swing.JLabel();
        txtVagones = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        txtChapa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtChapaActionPerformed(evt);
            }
        });

        jLabel1.setText("Chapa");

        jLabel2.setText("Color");

        txtColor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtColorKeyTyped(evt);
            }
        });

        jLabel3.setText("Fecha de Fabricación");

        txtFechaFabricacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFechaFabricacionKeyTyped(evt);
            }
        });

        jLabel4.setText("Cantidad de Combustible");

        txtCombustible.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCombustibleKeyTyped(evt);
            }
        });

        jLabel11.setText("Kilometraje Recorrido");

        txtKilometraje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKilometrajeActionPerformed(evt);
            }
        });
        txtKilometraje.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtKilometrajeKeyTyped(evt);
            }
        });

        jLabel5.setText("Precio de Reparación");

        txtPrecioReparacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPrecioReparacionKeyTyped(evt);
            }
        });

        jLabel6.setText("Costo de Reparación");

        txtCostoReparacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCostoReparacionKeyTyped(evt);
            }
        });

        jLabel7.setText("Fecha de Reparación");

        txtFechaReparacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFechaReparacionKeyTyped(evt);
            }
        });

        btnLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/3792081-broom-halloween-magic-witch_109049.png"))); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/_123048.png"))); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblPais.setText("Pais de Procedencia");

        txtPais.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPaisKeyTyped(evt);
            }
        });

        RadioButtonMonoplaza.setText("Monoplaza");

        moto.setText("Motocicleta");
        moto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        moto.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                motoStateChanged(evt);
            }
        });
        moto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                motoActionPerformed(evt);
            }
        });

        camioneta.setText("Camioneta");
        camioneta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        camioneta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                camionetaActionPerformed(evt);
            }
        });

        convertible.setText("Convertible");
        convertible.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        convertible.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                convertibleActionPerformed(evt);
            }
        });

        rastra.setText("Rastra");
        rastra.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rastra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rastraActionPerformed(evt);
            }
        });

        lblVelocidades.setText("Cantidad de Velocidades");

        sldVelocidades.setMajorTickSpacing(1);
        sldVelocidades.setMaximum(5);
        sldVelocidades.setMinorTickSpacing(1);
        sldVelocidades.setPaintLabels(true);
        sldVelocidades.setPaintTicks(true);
        sldVelocidades.setValue(0);

        lblVolumenMaximo.setText("Volumen Máximo");

        txtVolumenMaximo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtVolumenMaximoKeyTyped(evt);
            }
        });

        lblVolumenActual.setText("Volumen Actual");

        txtVolumenActual.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtVolumenActualKeyTyped(evt);
            }
        });

        radioButtonLujo.setText("Lujo");

        lblVagones.setText("Cantidad de Vagones");

        txtVagones.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtVagonesKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(RadioButtonMonoplaza)
                                    .addComponent(moto))
                                .addGap(18, 18, 18)
                                .addComponent(camioneta)
                                .addGap(18, 18, 18)
                                .addComponent(convertible)
                                .addGap(18, 18, 18)
                                .addComponent(rastra))
                            .addComponent(radioButtonLujo)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblVolumenMaximo)
                                    .addComponent(lblVolumenActual)
                                    .addComponent(lblVagones))
                                .addGap(58, 58, 58)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtVagones, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtVolumenMaximo, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtVolumenActual, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPais, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblVelocidades, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtPais, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(sldVelocidades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 40, Short.MAX_VALUE))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(moto)
                    .addComponent(rastra)
                    .addComponent(camioneta)
                    .addComponent(convertible))
                .addGap(30, 30, 30)
                .addComponent(RadioButtonMonoplaza)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPais, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblVelocidades)
                        .addGap(58, 58, 58)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblVolumenMaximo)
                            .addComponent(txtVolumenMaximo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(sldVelocidades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtVolumenActual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblVolumenActual))
                .addGap(18, 18, 18)
                .addComponent(radioButtonLujo)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVagones)
                    .addComponent(txtVagones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(107, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel11))
                        .addGap(71, 71, 71)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtChapa, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtColor, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtKilometraje, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtFechaFabricacion, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCombustible, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPrecioReparacion, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCostoReparacion, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtFechaReparacion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(95, 95, 95)
                        .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtChapa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(txtColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtFechaFabricacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtCombustible, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(txtKilometraje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtPrecioReparacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtCostoReparacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(txtFechaReparacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLimpiar)
                    .addComponent(btnGuardar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtKilometrajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKilometrajeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKilometrajeActionPerformed

    private void txtChapaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtChapaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtChapaActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        limpiar();
        txtChapa.setText("");
        txtColor.setText("");
        txtCombustible.setText("");
        txtCostoReparacion.setText("");
        txtFechaFabricacion.setText("");
        txtFechaReparacion.setText("");
        txtKilometraje.setText("");
        txtPrecioReparacion.setText("");
        RadioButtonMonoplaza.setSelected(false);
        txtPais.setText("");
        sldVelocidades.setValue(0);
        txtVolumenMaximo.setText("");
        txtVolumenActual.setText("");
        radioButtonLujo.setSelected(false);
        txtVagones.setText("");
        
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        ValidarCampos validar = new ValidarCampos();
        boolean flag = true;
        String mensaje = "Compruebe los siguientes parametros";

        if(!validar.comprobarFecha(txtFechaFabricacion.getText())){
            flag = false;
            mensaje += "\n -Formato de fecha de fabricación inválido: dd/mm/aa";
        }
        
        if(!validar.comprobarFecha(txtFechaReparacion.getText())){
            flag = false;
            mensaje += "\n -Formato de fecha de reparación inválido: dd/mm/aa";
        }
        
        if(validar.convertirEntero(txtPrecioReparacion.getText()) < validar.convertirEntero(txtCostoReparacion.getText())){
            flag = false;
            mensaje += "\n -El precio de reparación no debe ser menor que el costo";
        }
        
        if(flag){
            String chapa = txtChapa.getText();
            String color = txtColor.getText();
            double combustible = validar.convertirEntero(txtCombustible.getText());
            double costo = validar.convertirEntero(txtCostoReparacion.getText());
            String fechaReparacion = txtFechaReparacion.getText();
            String fechaFabricacion = txtFechaFabricacion.getText();
            double kilometraje = validar.convertirEntero(txtKilometraje.getText());
            double precio = validar.convertirEntero(txtPrecioReparacion.getText());
            if(moto.isSelected()){
                boolean monoplaza = RadioButtonMonoplaza.isSelected();
                String pais = txtPais.getText();
                Vehiculo v = new Motocicleta(monoplaza, pais, chapa, color, fechaFabricacion, combustible, kilometraje, precio, fechaReparacion, costo);
                taller.agregarVehiculo(v);
                JOptionPane.showMessageDialog(this, "Motocicleta guardada correctamente");
            } else if(camioneta.isSelected()){
                int velocidades = sldVelocidades.getValue();
                double volumenMaximo = validar.convertirEntero(txtVolumenMaximo.getText());
                double volumenActual = validar.convertirEntero(txtVolumenActual.getText());
                Vehiculo v = new Camioneta(volumenMaximo, volumenActual, velocidades, chapa, color, fechaFabricacion, combustible, kilometraje, precio, fechaReparacion, costo);
                taller.agregarVehiculo(v);
                JOptionPane.showMessageDialog(this, "Camioneta guardada correctamente");
            } else if(convertible.isSelected()){
                int velocidades = sldVelocidades.getValue();
                boolean lujo = radioButtonLujo.isSelected();
                Vehiculo v = new Convertible(lujo, velocidades, chapa, color, fechaFabricacion, combustible, kilometraje, precio, fechaReparacion, costo);
                taller.agregarVehiculo(v);
                JOptionPane.showMessageDialog(this, "Convertible guardada correctamente");
            } else{
                int velocidades = sldVelocidades.getValue();
                int vagones = validar.convertirEntero(txtVagones.getText());
                Vehiculo v = new Rastra(vagones, velocidades, chapa, color, fechaFabricacion, combustible, kilometraje, precio, fechaReparacion, costo);
                taller.agregarVehiculo(v);
                JOptionPane.showMessageDialog(this, "Camioneta guardada satisfactoriamente");
            }
        } else{
            JOptionPane.showMessageDialog(this, mensaje);
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void txtVagonesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtVagonesKeyTyped
       char cog = evt.getKeyChar();
        if(Character.isLetter(cog))
        evt.consume();
    }//GEN-LAST:event_txtVagonesKeyTyped

    private void motoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_motoActionPerformed
        limpiar();
        RadioButtonMonoplaza.setVisible(true);
        lblPais.setVisible(true);
        txtPais.setVisible(true);
    }//GEN-LAST:event_motoActionPerformed

    private void txtColorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtColorKeyTyped
        char cog = evt.getKeyChar();
        if(Character.isDigit(cog))
        evt.consume();
    }//GEN-LAST:event_txtColorKeyTyped

    private void txtCombustibleKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCombustibleKeyTyped
        char cog = evt.getKeyChar();
        if(Character.isLetter(cog))
        evt.consume();
    }//GEN-LAST:event_txtCombustibleKeyTyped

    private void txtKilometrajeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtKilometrajeKeyTyped
        char cog = evt.getKeyChar();
        if(Character.isLetter(cog))
        evt.consume();
    }//GEN-LAST:event_txtKilometrajeKeyTyped

    private void txtPrecioReparacionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrecioReparacionKeyTyped
        char cog = evt.getKeyChar();
        if(Character.isLetter(cog))
        evt.consume();
    }//GEN-LAST:event_txtPrecioReparacionKeyTyped

    private void txtCostoReparacionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCostoReparacionKeyTyped
        char cog = evt.getKeyChar();
        if(Character.isLetter(cog))
        evt.consume();
    }//GEN-LAST:event_txtCostoReparacionKeyTyped

    private void motoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_motoStateChanged
       
    }//GEN-LAST:event_motoStateChanged

    private void camionetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_camionetaActionPerformed
        limpiar();
        lblVelocidades.setVisible(true);
        sldVelocidades.setVisible(true);
        lblVolumenMaximo.setVisible(true);
        txtVolumenMaximo.setVisible(true);
        lblVolumenActual.setVisible(true);
        txtVolumenActual.setVisible(true);
    }//GEN-LAST:event_camionetaActionPerformed

    private void convertibleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_convertibleActionPerformed
        limpiar();
        lblVelocidades.setVisible(true);
        sldVelocidades.setVisible(true);
        radioButtonLujo.setVisible(true);
    }//GEN-LAST:event_convertibleActionPerformed

    private void rastraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rastraActionPerformed
        limpiar();
        lblVelocidades.setVisible(true);
        sldVelocidades.setVisible(true);
        lblVagones.setVisible(true);
        txtVagones.setVisible(true);
    }//GEN-LAST:event_rastraActionPerformed

    private void txtPaisKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPaisKeyTyped
        char cog = evt.getKeyChar();
        if(Character.isDigit(cog))
        evt.consume();
    }//GEN-LAST:event_txtPaisKeyTyped

    private void txtVolumenMaximoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtVolumenMaximoKeyTyped
        char cog = evt.getKeyChar();
        if(Character.isLetter(cog))
        evt.consume();
    }//GEN-LAST:event_txtVolumenMaximoKeyTyped

    private void txtVolumenActualKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtVolumenActualKeyTyped
        char cog = evt.getKeyChar();
        if(Character.isLetter(cog))
        evt.consume();
    }//GEN-LAST:event_txtVolumenActualKeyTyped

    private void txtFechaFabricacionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFechaFabricacionKeyTyped
        char cog = evt.getKeyChar();
        if(Character.isLetter(cog))
        evt.consume();
    }//GEN-LAST:event_txtFechaFabricacionKeyTyped

    private void txtFechaReparacionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFechaReparacionKeyTyped
        char cog = evt.getKeyChar();
        if(Character.isLetter(cog))
        evt.consume();
    }//GEN-LAST:event_txtFechaReparacionKeyTyped

    public void limpiar(){
        RadioButtonMonoplaza.setVisible(false);
        lblPais.setVisible(false);
        txtPais.setVisible(false);
        lblVelocidades.setVisible(false);
        sldVelocidades.setVisible(false);
        lblVolumenMaximo.setVisible(false);
        txtVolumenMaximo.setVisible(false);
        lblVolumenActual.setVisible(false);
        txtVolumenActual.setVisible(false);
        radioButtonLujo.setVisible(false);
        lblVagones.setVisible(false);
        txtVagones.setVisible(false);
    }
    
    public void cargarDatos(Vehiculo v){
        txtChapa.setText(v.getChapa());
        txtColor.setText(v.getColor());
        txtCombustible.setText(Double.toString(v.getCantidadCombustible()));
        txtCostoReparacion.setText(Double.toString(v.getCostoReparacion()));
        txtFechaFabricacion.setText(v.getFechaFabricacion());
        txtFechaReparacion.setText(v.getFechaReparacion());
        txtKilometraje.setText(Double.toString(v.getKilometraje()));
        txtPrecioReparacion.setText(Double.toString(v.getPrecioReparacion()));
        if(v instanceof Motocicleta)
            moto.setSelected(true);
        else if(v instanceof Camioneta)
            camioneta.setSelected(rootPaneCheckingEnabled);
        else if(v instanceof Convertible)
            convertible.setSelected(rootPaneCheckingEnabled);
        else
            rastra.setSelected(rootPaneCheckingEnabled);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormInsertarVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormInsertarVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormInsertarVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormInsertarVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FormInsertarVehiculo dialog = new FormInsertarVehiculo(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton RadioButtonMonoplaza;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JRadioButton camioneta;
    private javax.swing.JRadioButton convertible;
    private javax.swing.ButtonGroup group1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblPais;
    private javax.swing.JLabel lblVagones;
    private javax.swing.JLabel lblVelocidades;
    private javax.swing.JLabel lblVolumenActual;
    private javax.swing.JLabel lblVolumenMaximo;
    private javax.swing.JRadioButton moto;
    private javax.swing.JRadioButton radioButtonLujo;
    private javax.swing.JRadioButton rastra;
    private javax.swing.JSlider sldVelocidades;
    private javax.swing.JTextField txtChapa;
    private javax.swing.JTextField txtColor;
    private javax.swing.JTextField txtCombustible;
    private javax.swing.JTextField txtCostoReparacion;
    private javax.swing.JTextField txtFechaFabricacion;
    private javax.swing.JTextField txtFechaReparacion;
    private javax.swing.JTextField txtKilometraje;
    private javax.swing.JTextField txtPais;
    private javax.swing.JTextField txtPrecioReparacion;
    private javax.swing.JTextField txtVagones;
    private javax.swing.JTextField txtVolumenActual;
    private javax.swing.JTextField txtVolumenMaximo;
    // End of variables declaration//GEN-END:variables
}
